[tool.poetry]
name = "homebrew-archimedes"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
arcl = "*"

[tool.poetry.dev-dependencies]
pyinstaller = "^5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
